name: Tasks API

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      working-directory: ./back-end
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    - name: Run poetry shell
      working-directory: ./back-end
      run: |
        poetry shell
